package todofile

import "strings"

import "os"

func WriteTodoFile(path string, items []TodoItem) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}

	var content strings.Builder
	content.WriteString("<!-- don't edit | todo file auto generated by todomgr -->\n")

	for _, item := range items {
		var todoLine strings.Builder
		todoLine.WriteString("\n")

		if item.Completed {
			todoLine.WriteString("- [x]")
		} else {
			todoLine.WriteString("- [ ]")
		}

		todoLine.WriteString(" ")
		todoLine.WriteString(item.Description)

		content.WriteString(todoLine.String())
	}

	file.WriteString(content.String())

	return nil
}
