package todofile

import "os"

func WriteTodoFile(path string, items []TodoItem) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}

	var content string = "<!-- don't edit | todo file auto generated by todomgr -->\n"

	for _, item := range items {
		var todoLine string = "\n"

		if item.Completed {
			todoLine += "- [x]"
		} else {
			todoLine += "- [ ]"
		}

		todoLine += " "
		todoLine += item.Description

		content += todoLine
	}

	file.WriteString(content)

	return nil
}
